### ISSUE TITLE
--import-mappings not working for Go

### ISSUE THREAD

**Issue by jajupreetam** [OpenAPITools/openapi-generator-cli#101]
I am runing below command to use my own type "CustomDateTime" defined  in "config" package and not to use time.Time
 in generated models.

openapi-generator-cli generate -g go-experimental -i api-docs.json -o ${CLIENTPATH} --import-mappings=config.CustomDateTime=myProject/config --type-mappings=time.Time=config.CustomDateTime

with this , i can see my struct got the "config.CustomDateTime" as datatype instead of time.Time, however it didnt added the import statement & hence there is compilation error in go file.

package hybris

type Cart struct {
	CreationTime                      *config.CustomDateTime          `json:"creationTime,omitempty"`
}

why the import-mappings is not working for go-experimental/go ?

**Comment by kay-schecker** [comment]
Please see #31
