### ISSUE TITLE
Method with Path variable

### ISSUE THREAD

**Issue by jtomekcz** [OpenAPITools/openapi-generator-cli#12]
Hello, i have problem with API, where is defined method with path variable (in case where given variable is defined via $ref). When i try generate code according to API, then is result following:
`-attribute paths.'/user/{idAccount}'. Declared path parameter idAccount needs to be defined as a path parameter in path or operation level`

```
...
  /user/{idAccount}/baseInfo:
    parameters:
      - $ref: "#/components/parameters/TrackingCallId"
      - $ref: "#/components/parameters/idAccount"
    post:
      tags:
        - "User"
      summary: "Create user"
      description: "Method to create user for given customer"
      operationId: "createUser"
...
components:
  parameters:
    idAccount:
      name: "idAccount"
      in: "path"
      required: true
      description: "Identification of CRM customer"
      schema:
        type: string
```
best regards - jt -

**Comment by wing328** [comment]
Can you try the latest master which should have the issue addressed with a newer version of parser?

**Comment by wing328** [comment]
I mean the latest master of OpenAPI Generator in https://github.com/OpenAPITools/openapi-generator.

You can find the JAR SNAPSHOT in the README.

**Comment by wing328** [comment]
If you still need help, please open an issue in https://github.com/OpenAPITools/openapi-generator instead.
