### ISSUE TITLE
[BUG] not usable with private repository

### ISSUE THREAD

**Issue by EstebanDugueperoux2** [OpenAPITools/openapi-generator-cli#130]
# 🐛 Bug Report:

### Describe the bug
Using openapi-generator-cli in a Jenkins based continuous integration without opened network route to outside, I can't use it because version-manager has hard-coded Nexus repo URL (https://repo1.maven.org/maven2/).

### Steps to Reproduce
1. Install openapi-generator-cli from npm repository (https://www.npmjs.com/package/@openapitools/openapi-generator-cli)
2. Execute openapi-generator-cli through a NPM script

### Expected behavior
Have a mean to specify a private Nexus repo instead of central one.

**Comment by kay-schecker** [comment]
Thanks for the hint. 👍 I will add a config option till the end of the week.

**Comment by EstebanDugueperoux2** [comment]
Thanks for your feedback.

In addition when testing in local where I have access to central Nexus through a corporate proxy I get following feedback on Windows from a either Powershell or old "MSDos" command line:

````
PS C:\Users\x180349\git\demo-sgs-webapp> openapi-generator-cli.cmd
Download 4.3.1 ...
Download failed, because of: "Request failed with status code 500"
(node:19016) UnhandledPromiseRejectionWarning: Error: Error: Unable to access jarfile C:\Users\x180349\sgwt-installer\nodist\bin\node_modules\@openapitools\openapi-generator-cli\versions\4.3.1.jar

    at C:\Users\x180349\sgwt-installer\nodist\bin\node_modules\@openapitools\openapi-generator-cli\main.js:598:32
    at ChildProcess.exithandler (child_process.js:302:5)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
(node:19016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:19016) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I don't understand this 500 Http code.
Do you know how to enable more verbose logs to have details about this 500 http code?

Another useful feature would be an option to disable download and another to specify where to look for local release of openapi-generator, perhaps in openapitools.json

**Comment by nilskuhn** [comment]
Same problem for me, a fix would be great!

**Comment by kay-schecker** [comment]
I've adjusted the cli to print more error details, also you can configure the download and query url in the config file like that:

```
{
  "$schema": "node_modules/@openapitools/openapi-generator-cli/config.schema.json",
  "spaces": 2,
  "generator-cli": {
    "version": "4.3.1",
    "repository": {
      "queryUrl": "https://search.maven.org/solrsearch/select?q=g:${group.id}+AND+a:${artifact.id}&core=gav&start=0&rows=200",
      "downloadUrl": "https://repo1.maven.org/maven2/${groupId}/${artifactId}/${versionName}/${artifactId}-${versionName}.jar"
    }
  }
}
```

The following placeholders are available:

groupId: org/openapitools
artifactId: openapi-generator-cli
group.id: org.openapitools
artifact.id: openapi-generator-cli

**Comment by kay-schecker** [comment]
FYI: Will be released soon

**Comment by EstebanDugueperoux2** [comment]
Thanks @kay-schecker for your fix.
I have tested it in 2 scenarios:

- On my local workstation, without specifying my internal corporate repository, i.e. using by default Maven central I get follow error from proxy:

```
Cannot initialize server context:handshake failed:server state 1:state 9:Application response 500 handshakefailed
```

I suspect http client used don't manage HTTP(S)_PROXY environment variables.
Do you use https://www.npmjs.com/package/http-service or https://www.npmjs.com/package/axios?

- When specifying my internal corporate repository in my openapitools.json I get following feedback:

```
Download 4.3.1 ...
Download failed, because of: "unable to get local issuer certificate"
```

While in my ~/.npmrc I have `strict-ssl=false`

Is it possible to have http request aware of npm config and proxy environment variables?

Best Regards and thanks for your efficient feedback.

**Comment by kay-schecker** [comment]
Could u try to set the env vars HTTP_PROXY and HTTPS_PROXY globally?

**Comment by EstebanDugueperoux2** [comment]
These env variables are set globally on my Windows settings.

**Comment by Zialus** [comment]
I'm facing the same issue.

I have env vars HTTP_PROXY and HTTPS_PROXY set up properly (other tools in the Jenkins pipeline are using the proxy without any problem).

**Comment by kay-schecker** [comment]
The environment variables HTTPS_PROXY and HTTP_PROXY are considered now.

**Comment by nilskuhn** [comment]
> I've adjusted the cli to print more error details, also you can configure the download and query url in the config file like that:
> 
> ```
> {
>   "$schema": "node_modules/@openapitools/openapi-generator-cli/config.schema.json",
>   "spaces": 2,
>   "generator-cli": {
>     "version": "4.3.1",
>     "repository": {
>       "queryUrl": "https://search.maven.org/solrsearch/select?q=g:${group.id}+AND+a:${artifact.id}&core=gav&start=0&rows=200",
>       "downloadUrl": "https://repo1.maven.org/maven2/${groupId}/${artifactId}/${versionName}/${artifactId}-${versionName}.jar"
>     }
>   }
> }
> ```

To use a private repository / Nexus to load `openapi-generator-cli` from, I would need to configure just a static `downloadUrl`. In a nexus, I don't have a `queryUrl` and [this](https://github.com/OpenAPITools/openapi-generator-cli/blob/cf2921d729d83263f78b94bbeabc65f4efc51823/lib/index.js#L29) looks like it is necessary and a special payload, returned from queryUrl is expected.

So I don't understand, how your fix would enable me to use / load openapi-generator-cli from a private nexus.

**Comment by EstebanDugueperoux2** [comment]
@nilskuhn 
I have the same issue that you.
In addition I have always a certificate issue which forbiden me to test.

**Comment by wing328** [comment]
As a workaround, you can clone http://github.com/openAPITools/openapi-generator/ and build the project locally so as to obtain the openapi-generator-cli.jar

**Comment by kay-schecker** [comment]
The query url is used only for the version manager. Please try to put in a fixed download url.

**Comment by Zialus** [comment]
> The query url is used only for the version manager. Please try to put in a fixed download url.

Actually it is used for regular downloads too

**Comment by kay-schecker** [comment]
I've tested the following configuration:

```
{
  "$schema": "node_modules/@openapitools/openapi-generator-cli/config.schema.json",
  "spaces": 2,
  "generator-cli": {
    "version": "5.0.0-beta2",
    "repository": {
      "downloadUrl": "https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/5.0.0-beta2/openapi-generator-cli-5.0.0-beta2.jar?test123"
    },
    "generators": {
        "default": {
        "glob": "docs/oas3/*.yaml",
        "generatorName": "typescript-angular",
        "output": "libs/oa/#{name}",
        "additionalProperties": {
          "providedInRoot": false,
          "fileNaming": "kebab-case",
          "apiModulePrefix": "#{Name}",
          "npmName": "@kay-schecker/#{name}"
        }
      }
    }
  }
}
```

And I started a debug proxy, on port 8888 and did set HTTP_PROXY for the first request and HTTPS_PROXY for the second call.

```
HTTP_PROXY=http://localhost:8888 openapi-generator-cli generate
HTTPS_PROXY=http://localhost:8888 openapi-generator-cli generate
```

As you can see there is no call to the query url and the proxy settings are working, because my proxy did record the request.

![image](https://user-images.githubusercontent.com/30752021/100851161-186ca480-3485-11eb-8c0c-74dceef1310c.png)


So i guess you've an issue with your corporate proxy ...

**Comment by nilskuhn** [comment]
Thanks for the info, that queryUrl isn't necessary, good to know.

But what you are showing here is: Loading openapi-generator-cli from public maven repository through an *http* proxy (in your test scenario a locally running instance instead of a corporate proxy). 

But what I would like to do is a different thing: We are using a private Nexus instance as a "proxy", mirroring public maven (and npm) repositories. I would like npx to use this nexus instead of public maven repository when installing openapi-generator-cli. 

My current workaround:

Because jar file of openapi-generator-cli doesn't exist on our nexus instance, I am not able to test whether it would work by configuring `downloadUrl` in openapitools.json. 
For the moment I solved this by a npm script, loading tarball from nexus (that one was already there), extract it and use local binary afterwards:
```
"scripts": {
  ...
  "pregenerate-api": "shx mkdir -p bin && curl -s -o ./openapi-generator-cli.tgz https://<domain/path/to/internal/nexus/repo>/@openapitools/openapi-generator-cli/-/openapi-generator-cli-1.0.18-4.3.1.tgz && tar xzf ./openapi-generator-cli.tgz && mv package/bin/openapi-generator* bin && rm -rf ./package ./openapi-generator-cli.tgz",
  "generate-api": "bin/openapi-generator generate -i ..."
}
```
But it would be much nicer, if it would be possible to load latest version via npx from (nexus mirrored) public maven repository.

I hope this clarifies the problem.

**Comment by Zialus** [comment]
So, let's start with the proxy(without config modifications):

I did a quick test on the pipeline (I picked a random mvn goal that needs to download some dependencies)

❌ `mvn versions:help` fails to download depedencies

```
[ERROR] Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.8.1:help (default-cli) on project standalone-pom: Execution default-cli of goal org.codehaus.mojo:versions-maven-plugin:2.8.1:help failed: Plugin org.codehaus.mojo:versions-maven-plugin:2.8.1 or one of its dependencies could not be resolved: Failed to collect dependencies at org.codehaus.mojo:versions-maven-plugin:jar:2.8.1 -> org.apache.maven.reporting:maven-reporting-impl:jar:3.0.0 -> org.apache.maven:maven-core:jar:3.0 -> org.apache.maven:maven-aether-provider:jar:3.0 -> org.sonatype.aether:aether-impl:jar:1.7: Failed to read artifact descriptor for org.sonatype.aether:aether-impl:jar:1.7: Could not transfer artifact org.sonatype.aether:aether-impl:pom:1.7 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: Name or service not known: Unknown host repo.maven.apache.org: Name or service not known -> [Help 1]
```

 ✅ `mvn versions:help -Djava.net.useSystemProxies=true` downloads everything just fine


This is the output when running openapi-generator-cli

```
Download 4.3.1 ...
Download failed, because of: "Request failed with status code 400"

Response:
cache-control no-cache
pragma no-cache
content-type text/html; charset=utf-8
proxy-connection close
connection close
content-length 1087

<HTML><HEAD>
 
 
 
 <TITLE>Request Error</TITLE>
 
 
 
 </HEAD>
 
 
 
 <BODY>
 
 
 
 <FONT face="Helvetica">
 
 
 
 <big><strong></strong></big><BR>
 
 
 
 </FONT>
 
 
 
 <blockquote>
 
 
 
 <TABLE border=0 cellPadding=1 width="80%">
 
 
 
 <TR><TD>
 
 
 
 <FONT face="Helvetica">
 
 
 
 <big>Request Error (invalid_request)</big>
 
 
 
 <BR>
 
 
 
 <BR>
 
 
 
 </FONT>
 
 
 
 </TD></TR>
 
 
 
 <TR><TD>
 
 
 
 <FONT face="Helvetica">
 
 
 
 Your request could not be processed. Request could not be handled
 
 
 
 </FONT>
 
 
 
 </TD></TR>
 
 
 
 <TR><TD>
 
 
 
 <FONT face="Helvetica">
 
 
 
 This could be caused by a misconfiguration, or possibly a malformed request.
 
 
 
 </FONT>
 
 
 
 </TD></TR>
 
 
 
 <TR><TD>
 
 
 
 <FONT face="Helvetica" SIZE=2>
 
 
 
 <BR>
 
 
 
 For assistance, contact your network support team.
 
 
 
 </FONT>
 
 
 
 </TD></TR>
 
 
 
 </TABLE>
 
 
 
 </blockquote>
 
 
 
 </FONT>
 
 
 
 </BODY></HTML>
```

`wget --no-proxy https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/4.3.1/openapi-generator-cli-4.3.1.jar` fails as expected

```
--2020-12-02 14:19:12--  https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/4.3.1/openapi-generator-cli-4.3.1.jar
Resolving repo1.maven.org (repo1.maven.org)... failed: Name or service not known.
wget: unable to resolve host address 'repo1.maven.org'
```

`wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/4.3.1/openapi-generator-cli-4.3.1.jar` uses the proxy env variables and works

**Comment by Zialus** [comment]
In the case of the private nexus I just now realized that I'm able to make it work by unsetting the proxy env variables, my bad.

BTW @EstebanDugueperoux2 the option you want isn't  `strict-ssl=false` on `~/.npmrc` but actually `NODE_TLS_REJECT_UNAUTHORIZED=0` as an env variable

**Comment by Zialus** [comment]
@kay-schecker as a follow-up to my last comment, is there any way you can respect the NO_PROXY env var too?

Related PRs:
https://github.com/axios/axios/pull/691
https://github.com/axios/axios/pull/1693
