### ISSUE TITLE
Release a Semver compliant NPM version

### ISSUE THREAD

**Issue by PierreBesson** [OpenAPITools/openapi-generator-cli#14]
Currently the version tag for openapi-generator-cli releases doesn't respect Semver (Semantic Versioning). For example the current release is `0.0.9-3.3.4`.

I understand the rationale of being able to select both the CLI version and openapi-generator version at once but sadly this is inconsistent with the Semver convention.

As a first step, I'm proposing to add an extra published version which would only contain the cli version and would imply the latest openapi-generator release. This way we can keep the current versioning but users could also simply set the version to a semver version (for example: `0.0.9`)

**Comment by kay-schecker** [comment]
SemVer introduced with v2.x.x
