### ISSUE TITLE
[BUG][typescript-axios] For nested fields there is  `& AnyType` generated

### ISSUE THREAD

**Issue by LukaszKuciel** [OpenAPITools/openapi-generator-cli#144]
# 🐛 Bug Report:

### Describe the bug
Whenever there is nested object defined in request body there is ` & AnyType` added to actuall type of nested field. When I'm trying to build api client I get following error:

```cli
api.ts:767:36 - error TS4033: Property 'createdAt' of exported interface has or is using private name 'AnyType'.

767     createdAt?: DateRangeRequest & AnyType;
```

### Steps to Reproduce
1. Create swagger request body definition that has nested fields
2. run `openapi-generator-cli generate`
3. Check generated api.ts for `& AnyType` occurance 
4. Build api client
5. See build error `Property 'your_prop' of exported interface has or is using private name 'AnyType'.`

### Expected behavior
There shouldn't be ` & AnyType` added to api.ts

### Screenshots
![image](https://user-images.githubusercontent.com/35846271/100152762-7b69a480-2ea3-11eb-8f3c-e7c0e0721dd4.png)

### Operation System (please complete the following information):
 - OS: Ubuntu
 - Version 20.04

### Package System (please complete the following information):
 - Version 2.1.7

### Additional context
I found this issue in main openapi generator https://github.com/OpenAPITools/openapi-generator/issues/6332. It seems like it was resolved in openapi-generator but not applied on this npm wrapper.

**Comment by LukaszKuciel** [comment]
Ok, for now, I resolved this issue by downgrading generator to version "4.3.0" inside my openapitools.json

**Comment by kay-schecker** [comment]
rejected. Read the Bug Notes!
