### ISSUE TITLE
[BUG] Spec source from `inputSpec` is ignored

### ISSUE THREAD

**Issue by pfeileon** [OpenAPITools/openapi-generator-cli#163]
# 🐛 Bug Report:

### Describe the bug
Property `inputSpec` is ignored, which makes using remote specs impossible. According to the json schema this should be supported:
```json
"inputSpec": {
          "type": "string",
          "description": "location of the OpenAPI spec, as URL or file (required if not loaded via config using -c)"
        },
```
https://github.com/OpenAPITools/openapi-generator-cli/blob/master/apps/generator-cli/src/config.schema.json

### Expected behavior
Defining an HTTP URL to a remote spec via `inputSpec` should be possible.

### Additional context
The method `generate` in `generator.service.ts` ignores the `inputSpec` property and only considers `glob`.

**Comment by kay-schecker** [comment]
Thanks @pfeileon I‘ll have a look these days.

**Comment by pfeileon** [comment]
It seems to work with an empty local spec file and a working URL:
```
"glob": "empty-spec.json",
"inputSpec": "http://path.to/spec"
```
The CLI then uses the value of "glob" as `#{name}`.

If this is intended, there is no bug, but the documentation is incomplete.

**Comment by ChristopherL-STCU** [comment]
Thanks for the research @pfeileon. Unfortunately I was not able to get that to work for me using 5.0.0-beta3, I imagine I do not have something quite right in my configuration. I'm not quite sure if `inputSpec` was supposed to include an actual file or only the directory. I tried both ways and could not get either to work.

```
"glob": "test.yaml"
"inputSpec": "https://example.com/specs/test.yaml"
```

**Comment by pfeileon** [comment]
No, it works with an endpoint which includes the spec's content in its response body.

**Comment by gabormagyar** [comment]
@kay-schecker `config.schema.json` still includes `glob` as a required property, so I still can't create a globless generator config unless I remove the schema or ignore the warning
