### ISSUE TITLE
Update npm version from 4.0.0-beta3 to 4.0.0

### ISSUE THREAD

**Issue by saschat** [OpenAPITools/openapi-generator-cli#17]
Given that 4.0.0 was released 15 days ago and npm release was done 14 days ago I am assuming this happend by mistake. It would be awesome if you could update the release. Thanks a ton!

**Comment by wing328** [comment]
We'll release 4.0.1 this week so that should fix the issue (which means the latest will be 4.0.1 after the release this weekend)

**Comment by wing328** [comment]
now 4.0.0 is installed (instead of 4.0.1). I'm looking into the issue later this coming week.

If anyone wants to help, please feel free to submit a PR.

**Comment by wing328** [comment]
the latest has this fixed. please check when you've time.
