### ISSUE TITLE
[BUG] json configuration is ignored

### ISSUE THREAD

**Issue by strowk** [OpenAPITools/openapi-generator-cli#185]
# 🐛 Bug Report:

### Describe the bug
openapitools.json is ignored

### Steps to Reproduce
1. Place any spec in file api.yaml
2. configure openapitools.json as following

```
{
  "$schema": "node_modules/@openapitools/openapi-generator-cli/config.schema.json",
  "spaces": 2,
  "generator-cli": {
    "version": "4.3.1",
    "v3.0": { 
      "glob": "api.yaml",
      "generatorName": "typescript-fetch",
      "output": "#{cwd}/src/api",
      "additionalProperties": {
        "typescriptThreePlus": true

      }
    }
  }
}
```
3. ` yarn add --dev  @openapitools/openapi-generator-cli `
4. ` yarn openapi-generator-cli generate`
5. "[error] Required option '-i' is missing"

### Expected behavior
api.yaml is used to generate spec

### Operation System:
 - OS: Ubuntu
 - Version  20.04

### Package System:
 - yarn
 - Version 1.22.5

**Comment by kay-schecker** [comment]
Your config is wrong, Please search for existing issue before opening a new one.

Please see: https://github.com/OpenAPITools/openapi-generator-cli/issues/43
