### ISSUE TITLE
[BUG] Version Manager does not wait for the writeStream to end before resolving download

### ISSUE THREAD

**Issue by NicolasVargas** [OpenAPITools/openapi-generator-cli#198]
# 🐛 Bug Report:

### Describe the bug
Sometimes, running on CI (Jenkins), the generator fails because Java throws an error saying that the jar file in invalid while it is valid.

```shell
(node:61381) UnhandledPromiseRejectionWarning: Error: Error: Invalid or corrupt jarfile /my/jenkins/job/workspace
at Object (/my/jenkins/job/workspacenode_modules/@openapitools/openapi-generator-cli/main.js:613:32)
    at ChildProcess.exithandler (child_process.js:296:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:606:12)
```

This issue seems to happen because, when the VersionManagerService downloads the .jar file, the `download` method waits for the download stream to end to resolve while it does not wait for the write stream to end. So the generator launches the java process while the .jar file it is still incomplete and java throws this error.
If I download the so called incomplete file on my local machine, its works perfectly and if i launch again my jenkins job without clearing the workspace, the generator does not fail.

### Package System (please complete the following information):
 - Node  v10.13.0
 - Jenkins v2.60.3
 - Java JDK 1.8

### Additional context
I notice this issue on CI and not on my local machine. I suppose that it could also appear there but since the job is launched many times in CI during the day, cleans the workspace on each build and my jenkins machine is way faster than my local one, i have less chances to notice it on my local machine too.

Based on the [Node JS - fs documentation](https://nodejs.org/api/stream.html#stream_event_finish), here is a proposal. I'm sorry, i didn't setup my workspace for this project :

```typescript
  // apps/generator-cli/src/app/services/version-manager.service.ts
 async download(versionName: string) {
    // [...]

    try {
      await this.httpService
        .get<Stream>(downloadLink, { responseType: 'stream' })
        .pipe(switchMap(res => new Promise(resolve => {
            fs.ensureDirSync(this.storage);
            const file = fs.createWriteStream(filePath);
            res.data.pipe(file);
            // previous code 
            // res.data.on('end', resolve);
            // new code 
            file.on('finish', resolve);
          })
        )).toPromise();
   // [...]
  }
```

**Comment by kay-schecker** [comment]
Thanks for reporting the issue, I'll check it right now

**Comment by notbenj** [comment]
Thanks for such a fast fix!
