### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mateja176** [OpenAPITools/openapi-generator-cli#209]
# ⚠️ Important Notice

### Please differentiate the bug

This repository is not responsible for the actual code generation. If you have problems with the code generation, please open the bug at [OpenAPITools/openapi-generator](https://github.com/OpenAPITools/openapi-generator). 

Please also check if the bug is already known before you open a new bug.

----------------------------------------------------------------------------

# 🐛 Bug Report:

### Steps to Reproduce
1. `npx create-strapi-app my-app --quickstart`
2. `cd my-app`
3. `yarn strapi install documentation`
4. `code `extensions/documentation/documentation/1.0.0/full_documentation.json``
5. `ctrl+f`
6. `=`
7. You should be able to see a section similar to 
```json
          {
            "name": "=",
            "in": "query",
            "required": false,
            "description": "Get entries that matches exactly your input",
            "schema": {
              "type": "string"
            },
            "deprecated": false
          },
``` 
8. `mkdir client`
9. `npx openapi-generator-cli generate -i extensions/documentation/documentation/1.0.0/full_documentation.json -g typescript-fetch -o client --additional-properties=typescriptThreePlus=true  --skip-validate-spec`
10. `code client/apis/UsersPermissionsUserApi.ts`
11. `:113` (Around the line 113 there should be a syntax error)
```ts
        if (requestParameters. !== undefined) {
            queryParameters['&#x3D;'] = requestParameters.;
        }
```

### Expected behavior
The following code is generated instead
```ts
        if (requestParameters['='] !== undefined) {
            queryParameters['&#x3D;'] = requestParameters['='];
        }
```

### Screenshots
![Screenshot from 2021-01-04 16-08-34](https://user-images.githubusercontent.com/33357948/103549109-2314c200-4ea7-11eb-863c-d2c60ce40d4d.png)

![Screenshot from 2021-01-04 16-07-54](https://user-images.githubusercontent.com/33357948/103549046-0b3d3e00-4ea7-11eb-8742-efd1102cf25d.png)

### Operation System (please complete the following information):
 - OS: Ubuntu
 - Version: 20.04

### Package System (please complete the following information):
 - Version: `^2.1.16`

**Comment by kay-schecker** [comment]
⚠️ Important Notice

Please differentiate the bug

This repository is not responsible for the actual code generation. If you have problems with the code generation, please open the bug at OpenAPITools/openapi-generator.

Please also check if the bug is already known before you open a new bug.
