### ISSUE TITLE
[BUG] Download of openapi-generator client not possible behind corporate firewall

### ISSUE THREAD

**Issue by bjesuiter** [OpenAPITools/openapi-generator-cli#235]
# 🐛 Bug Report:

### Describe the bug
Request fails with status code 500 when trying to install behind a corporate firewall.

### Steps to Reproduce
1. Block internet if connection does not go through proxy

### Expected behavior
Jar will be downloaded correctly

### Screenshots

![grafik](https://user-images.githubusercontent.com/2365676/105758690-d37a6100-5f4f-11eb-84d7-75aef5f86f28.png)

### Operation System (please complete the following information):
 - OS: Windows 10 
 - Version 1809 (Build 17763.1697)

### Package System (please complete the following information):
 - NPM Version 6.14.8

**Comment by dolanmiu** [comment]
Having the same issue, any update or alternative?

**Comment by wing328** [comment]
A workaround is to download the openapi-generator-cli JAR manually, e.g.
```
wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/5.0.1/openapi-generator-cli-5.0.1.jar -O openapi-generator-cli.jar
```

**Comment by dolanmiu** [comment]
@wing328 Which folder do you download the jar file to? After this, will it stop trying to call the internet?

**Comment by prince-chrismc** [comment]
For the next guy who needs this...

You can now specify the URL mirrors to local servers

```json
{
    "$schema": "./node_modules/@openapitools/openapi-generator-cli/config.schema.json",
    "spaces": 2,
    "generator-cli": {
        "version": "5.1.1",
        "storageDir": "./openapitools-download",
        "repository": {
            "queryUrl": "http://mvn-search-proxy/select?q=g:${group.id}+AND+a:${artifact.id}&core=gav&start=0&rows=200",
            "downloadUrl": "http://mvn-dev-proxy/${groupId}/${artifactId}/${versionName}/${artifactId}-${versionName}.jar"
        }
    }
}
```

**Comment by kay-schecker** [comment]
Closed because there is a workaround

**Comment by JohannesHoppe** [comment]
@prince-chrismc wrote:
> You can now specify the URL mirrors to local servers

Thank you for this great tip. Could you please explain to me where the internal proxy comes from? Have you set up your own proxy for this (if so, do you perhaps have an example 😊) or does this maybe already exist as a feature of e.g. Nexus?

**Comment by prince-chrismc** [comment]
This was already in place at my last job for other services.

We used JFrog's Artifactory which has excellent "raw" proxy support. (Shameless plug since I know work for them). They have a community edition you can self host for free.

Nexus should be able to do it as well but if it's not maven the stability might not be there.

**Comment by JohannesHoppe** [comment]
@prince-chrismc Thank you very much for this detailed explanation! 🙂 👍
