### ISSUE TITLE
[missing feature] custom generators on classpath are not visible

### ISSUE THREAD

**Issue by SardarNL** [OpenAPITools/openapi-generator-cli#237]
# Custom generators are not visible to openapi-generator

Custom generators can be shipped as `.jar` file with codegen config and templates. This works fine with `maven`/`gradle` plugins, just add the `.jar` with a custom generator to dependencies. However, this will not work with `openapi-generator-cli` because [generator .jar is called using `-jar` option](https://github.com/OpenAPITools/openapi-generator-cli/blob/master/apps/generator-cli/src/app/services/pass-trough.service.ts#L89). When java is started with `-jar` option, [then `-cp` (classpath) option is ignored](https://docs.oracle.com/javase/7/docs/technotes/tools/solaris/java.html#jar).

A solution to this could be use of class path and main class explicitly
```
  java -cp "${userProvidedClasspath}:${this.versionManager.filePath()}" org.openapitools.codegen.OpenAPIGenerator ...
```
This will work the same as with `-jar` option, but provides the user with an option to declare custom generator.

### Steps to Reproduce

1. Make a[ new custom generator](https://openapi-generator.tech/docs/new-generator)
2. Add script to `package.json` with `JAVA_OPTS='-cp custom-generator.jar' openapi-generator-cli list`
2. You will not see the generator because `-cp` option is ignored

### Expected behavior
A mechanism to add custom `.jar` files to classpath. This will make it possible to ship custom generator as a `.jar` file.

I can make a pull request with this fix if you approve this idea. `PassThroughService` can simply check if class path extensions are provided. If not, then run generator with `-jar` option. Otherwise, assemble class path and run main class directly.

**Comment by mcaden** [comment]
I implemented the feature but I missed how it was originally requested to accept the `-cp` argument. Rather than intercept a provided `-cp` I implemented it as a custom parameter that changes the behavior. Not sure if this is preferable or not.

Usage:
`-custom-generator=my-generator.jar`

**Comment by SardarNL** [comment]
Tested PR above, it works. This allows us to `--custom-generator` our extensions/generators while benefitting from standardly built main generator.
