### ISSUE TITLE
prevent jar from being downloaded everytime when generating

### ISSUE THREAD

**Issue by japrescott** [OpenAPITools/openapi-generator-cli#239]
Great work with the 5.0.0 release and all its improvements!

I noticed that the jar is being downloaded everytime I run `npx @openapitools/openapi-generator-cli@2.1.17 generate -i api.yml`? Given that the version is "hardcoded" into the `config.yml` that is generated on first-run, it is unclear to me why it needs to download the jar every time. I saw I can download the [jar file separately](https://github.com/OpenAPITools/openapi-generator#13---download-jar) but didnt find a way how to pass the jar location to the openapi-generator-cli.

Did I overlook the documentation?

**Comment by wing328** [comment]
Run `npm install @openapitools/openapi-generator-cli` (ref: https://github.com/OpenAPITools/openapi-generator-cli#installation) to install the CLI wrapper first, and then run the following to generate code:
```
openapi-generator-cli generate -i api.yml -g java -o /tmp/java/
```

**Comment by japrescott** [comment]
@wing328 thank you
