### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dmitriy-pisarevskiy** [OpenAPITools/openapi-generator-cli#267]
Hi!
How I can keep original names in models?
Instead of '@odata.count' got odata_count
How can I fix it using openapi-generator-cli?

swagger JSON:
![image](https://user-images.githubusercontent.com/70516019/108312154-38447680-71f1-11eb-8983-4d0035d413a6.png)
Axios typescript model interface with Odata:
![image](https://user-images.githubusercontent.com/70516019/108312172-3ed2ee00-71f1-11eb-88ee-52f0e7372fc3.png)

**Comment by dmitriy-pisarevskiy** [comment]
@kay-schecker so, why you closed this? do you have a solution for this?

**Comment by kay-schecker** [comment]
Because of:

```
# ⚠️ Important Notice

### Please differentiate the bug

This repository is not responsible for the actual code generation. If you have problems with the code generation, please open the bug at [OpenAPITools/openapi-generator](https://github.com/OpenAPITools/openapi-generator). 

Please also check if the bug is already known before you open a new bug.

----------------------------------------------------------------------------
```
