### ISSUE TITLE
openapi-generator.jar corrupt (v1.0.9 packages)

### ISSUE THREAD

**Issue by tmakin** [OpenAPITools/openapi-generator-cli#28]
Latest 1.0.9 packages appear to have an issue with the jar from maven:

Repro steps:
```
> npm i @openapitools/openapi-generator-cli@1.0.9-4.2.3 -g
> openapi-generator

Output:
Error: Invalid or corrupt jarfile C:\...\npm\node_modules\@openapitools\openapi-generator-cli\bin\openapi-generator.jar
```

This file:
`node_modules\@openapitools\openapi-generator-cli\bin\openapi-generator.jar`

Contains an http redirect message:
```
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
</body>
</html>
```

**Comment by kimsey0** [comment]
Yep, looks like the download moved from something like `https://search.maven.org/remotecontent?filepath=org/openapitools/openapi-generator-cli/4.2.3/openapi-generator-cli-4.2.3.jar` to something like `https://repo1.maven.org/fromsearch?filepath=org/openapitools/openapi-generator-cli/4.2.3/openapi-generator-cli-4.2.3.jar`. [The download code](https://github.com/OpenAPITools/openapi-generator-cli/blob/52362b602c565b0d65247f362cbedf5b23e91868/lib/index.js#L70) uses the standard library `https` module, which doesn't automatically follow redirects.

It could be solved by:
1. Changing the base download URL used to `https://repo1.maven.org/fromsearch`, but I'm not sure if hardcoding that is best practice.
2. Manually handling the redirect.
3. Switching to another request library that can handle redirects automatically.

**Comment by Nowheresly** [comment]
Maybe this lib could help fixing the issue:

[https://github.com/follow-redirects/follow-redirects](https://github.com/follow-redirects/follow-redirects)

**Comment by wing328** [comment]
Let me take a look in an hour.


在 2020年1月31日週五 下午9:44，Sylvere Richard <notifications@github.com> 寫道：

**Comment by wing328** [comment]
Working on a fix ...

**Comment by wing328** [comment]
Fixed with https://github.com/OpenAPITools/openapi-generator-cli/commit/b4826accb739258a6732f157e3a1a54346522b21

**Comment by tmakin** [comment]
@wing328 All good now. Many thanks for speedy turnaround.
