### ISSUE TITLE
[BUG] Self signed certificate issue

### ISSUE THREAD

**Issue by sherrera-hx** [OpenAPITools/openapi-generator-cli#298]
# 🐛 Bug Report:

### Describe the bug
After installing openapi generator, when try to use it has self signed certificate issue

### Steps to Reproduce
1. Install open api
`npm install -g @openapitools/openapi-generator-cli`
2. run openapi-generation-cli version or any other command

### Expected behavior
See the version of the generaton

### Screenshots
![image](https://user-images.githubusercontent.com/73550939/110634644-f623aa80-8188-11eb-864f-cfa82df13d67.png)

### Operation System (please complete the following information):
 - OS: windows
 - Version 10

### Package System (please complete the following information):
 - Version latest

### Additional context
I am inside corporate network

**Comment by kay-schecker** [comment]
Please try to set the ENV vars as described here: https://levelup.gitconnected.com/how-to-resolve-certificate-errors-in-nodejs-app-involving-ssl-calls-781ce48daded
