### ISSUE TITLE
[BUG] Cli does not work is the same as openapitool.json

### ISSUE THREAD

**Issue by jogelin** [OpenAPITools/openapi-generator-cli#334]
# 🐛 Bug Report:

### Describe the bug
Rune openapi-generator-cli failed on input globs

### Steps to Reproduce
```
❯ npx openapi-generator-cli generate -g typescript-angular -o "./libs/api/src/lib/generated/#{name}" -i "./libs/api/src/lib/*/api-*.yaml" -c "libs/api/openapi-config.json"
[error] Found unexpected parameters: [./libs/api/src/lib/api-one/api-one.yaml, ./libs/api/src/lib/api-two/api-two.yaml]

See 'openapi-generator-cli help' for usage.
```

### Expected behavior
This is working if I use the `openapitool.json` file:
```
{
  "$schema": "node_modules/@openapitools/openapi-generator-cli/config.schema.json",
  "spaces": 2,
  "generator-cli": {
    "version": "4.3.1",
    "generators": {
      "v2.0": {
        "generatorName": "typescript-angular",
        "output": "./libs/api/src/lib/generated/#{name}",
        "glob": "./libs/api/src/lib/*/api-*.yaml",
        "additionalProperties": {
          "ngVersion": "11.2.2",
          "supportsES6": "true",
          "withInterfaces": true,
          "stringEnums": true,
          "modelNameSuffix": "Dto"
        }
      }
    }
  }
}

```

I expect the command line to work in the same way. It is finding the list of yaml files so the glob pattern is working.

It is also working if I specify one file

**Comment by wing328** [comment]
```
-i "./libs/api/src/lib/*/api-*.yaml"
```
openapi-generator doesn't support multiple OpenAPI specification files as the input.

Please use a script to loop through the spec files (yaml/json) instead.

**Comment by wing328** [comment]
For issues with openapi-generator-cli JAR itself, please open an issue in the https://github.com/openAPITools/openapi-generator/ repo.

**Comment by jogelin** [comment]
@wing328 
> ```
> -i "./libs/api/src/lib/*/api-*.yaml"
> ```
> 
> openapi-generator doesn't support multiple OpenAPI specification files as the input.
> 
> Please use a script to loop through the spec files (yaml/json) instead.

My bug is more related to `openapi-generator-cli`. It is not clear that the command line is not working in the same way as the `openapitool.json` file
