### ISSUE TITLE
[Support] How to use open api generator cli in monorepo architecture (Nrwl/nx)

### ISSUE THREAD

**Issue by jogelin** [OpenAPITools/openapi-generator-cli#336]
After some investigation, I have some difficulties to setup `openapi-generator-cli` in a monorepo architecture.

**Goal: Generate the API only for a specific project**

- I tried to duplicate `openapitool.json` in each project but I didn't find a way to provide the path of the file when running the command. Only next to the `package.json` ?
- Could be a generator key inside a global `openapitool.json` but I didn't find a way to provide the generator key of the file when running the command. Only for console logging ?
- I tried to customize the input of a command but #334 

I am working in a [Nrwl/Nx architecture](https://nx.dev/) like this project. Do you think a builder would be justified in this repository ?

**Comment by wing328** [comment]
> Do you think a builder would be justified in this repository ?

If it's not too much work, a PR to show exactly what change you would like to make would be helpful as a starting point for further discussion.

**Comment by jogelin** [comment]
For the moment I just created something like this:

```
import { spawn } from 'child_process';
import { resolve } from 'path';
import { BuilderContext, BuilderOutput, createBuilder } from '@angular-devkit/architect';
import { OpenapiBuilderSchema } from './schema';

async function runBuilder(options: OpenapiBuilderSchema, context: BuilderContext): Promise<BuilderOutput> {
  const {
    workspaceRoot,
    target: { project },
  } = context;
  const projectMetadata = await context.getProjectMetadata(project);
  const { root: projectRoot } = projectMetadata as {
    root: string;
    target: string;
    configuration: string;
  };

  const openapiGeneratorCliCmd = resolve(workspaceRoot, 'node_modules', '.bin', 'openapi-generator-cli');
  const openapiGeneratorArgsCmd = ['generate'];
  const processOptions = {
    cwd: resolve(workspaceRoot, projectRoot),
    shell: true,
  };

  process.env.PWD = processOptions.cwd;
  const child = spawn(openapiGeneratorCliCmd, openapiGeneratorArgsCmd, processOptions);

  return new Promise<BuilderOutput>((res) => {
    process.on('exit', () => child.kill());

    child.stdout.on('data', (data) => {
      context.logger.info(data.toString());
    });

    child.stderr.on('data', (data) => {
      context.logger.error(data.toString());
    });

    child.on('close', (code) => {
      res({ success: code === 0 });
    });
  });
}

export default createBuilder(runBuilder);

```

then I just have a new openapi target in my `workspace.json` that could be use like `nx run <projectName>:openapi`

This is allowing to have an `openapitool configuration` per project.

The best approach would be to use directly the openapi generator but then `openapi-generator-cli` will be useless.

**Comment by kay-schecker** [comment]
Hi I'll have a look during the next days.

**Comment by kay-schecker** [comment]
closed, please see --generator-key
