### ISSUE TITLE
Where can I find changelog/version history/tags to decide to upgrade or not?

### ISSUE THREAD

**Issue by jfoliveira** [OpenAPITools/openapi-generator-cli#34]
Running `npm outdated` it makes me aware that a new `openapi-generator-cli` version is available:
```javascript
$ npm outdated
Package                                   Current        Wanted        Latest
@openapitools/openapi-generator-cli  1.0.13-4.3.1  1.0.13-4.3.1  1.0.15-4.3.1
```

I couldn't find any tags in this repository to check what has changed since the version that I am currently using (`1.0.13-4.3.1`).

What's the best way to see this package's version history so I can make a decision on updating to latest version or not?

**Comment by wing328** [comment]
The release note of `openapi-generator` can be found in https://github.com/OpenAPITools/openapi-generator/releases/
