### ISSUE TITLE
[BUG] author template throws error on -g, Found unexpected parameters

### ISSUE THREAD

**Issue by mckelveygreg** [OpenAPITools/openapi-generator-cli#368]
# 🐛 Bug Report:

### Describe the bug
`openapi-generator-cli author template -g java --library webclient` throws the error
```
[error] Found unexpected parameters: [-g, java, --library, webclient]
```

### Steps to Reproduce
1. Install >2.3.0
2. Run `openapi-generator-cli author template -g java --library webclient`

### Expected behavior
Extract templates
<2.3.0 appears to work fine?

### Operation System (please complete the following information):
 - OS: OSX
 - Version Big Sur 14.4

### Package System (please complete the following information):
 - Version 2.3.3
 - (5.1.1 of openapi jar)

### Additional context
Perhaps an issue with the new minor feature addition?
custom generators: added '-custom-generator' parameter fixes #237 (99c2351)

Also reported in [OpenAPI-Generator](https://github.com/OpenAPITools/openapi-generator/issues/9557) but it seems to be a cli issue?

**Comment by syndicatedshannon** [comment]
present in
NPM: @openapitools/openapi-generator-cli@2.3.10
JAR: 5.2.1

**Comment by wing328** [comment]
Use https://github.com/OpenAPITools/openapi-generator/issues/9557 for tracking instead.

Closing this one.

**Comment by badsyntax** [comment]
This is fixed with https://github.com/OpenAPITools/openapi-generator-cli/releases/tag/v2.4.0
