### ISSUE TITLE
[BUG] Download failed

### ISSUE THREAD

**Issue by polluks** [OpenAPITools/openapi-generator-cli#389]
### Description of the bug
The download directory is missing.

### Steps to Reproduce
````
$ openapi-generator-cli
Download 5.1.1 ...
Download failed, because of: "ENOENT: no such file or directory, mkdir '/usr/local/lib/node_modules/@openapitools/openapi-generator-cli/versions'"
(node:19377) UnhandledPromiseRejectionWarning: Error: Error: Unable to access jarfile /usr/local/lib/node_modules/@openapitools/openapi-generator-cli/versions/5.1.1.jar

    at Object (/usr/local/lib/node_modules/@openapitools/openapi-generator-cli/main.js:621:32)
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
(node:19377) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:19377) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
````

### Expected behavior
Automatically creation of `versions` directory.

### Operation System:
 - OS: Debian on WSL2
 - Version 10
 - Linux XXX 4.4.0-19041-Microsoft #488-Microsoft Mon Sep 01 13:43:00 PST 2020 x86_64 GNU/Linux

### Package System:
 - Version 5.1.1

### Workaround
`mkdir /usr/local/lib/node_modules/@openapitools/openapi-generator-cli/versions`

**Comment by kay-schecker** [comment]
The directory will be created automatically. Could it be that it's a permission issue?

**Comment by polluks** [comment]
I see. Maybe an NTFS issue?

**Comment by kay-schecker** [comment]
Good question. Does this issue still exist in the latest version?

**Comment by wing328** [comment]
Closing this as there's no update. Let us know if you still need help.

Another option is to use the Docker images: https://hub.docker.com/r/openapitools/openapi-generator-cli
