### ISSUE TITLE
there are releases on npm that or not on github

### ISSUE THREAD

**Issue by japrescott** [OpenAPITools/openapi-generator-cli#39]
as the title says, there are new releases on npm that or not visible on github and there is also no changelog/history suggesting anything changed. Looking at the commits, it is to a certain point visible but the release `1.0.18-4.3.1` comes with absolute no context. What is the reason for this?

**Comment by kay-schecker** [comment]
Thats because the versions are generated automatically based on https://github.com/OpenAPITools/openapi-generator .

**Comment by wing328** [comment]
For changelog/history, please refer to https://github.com/OpenAPITools/openapi-generator/releases

**Comment by japrescott** [comment]
@kay-schecker @wing328
Thank you for your answers, I am aware of the main releases of the generator but that doesn't reflect the changes of the npm versions. What has changed between `1.0.10-4.3.1` and `1.0.18-4.3.1`? Where can I find that info? There are 3 commits since a commit talking about 1.0.10. How can 8 consecutive releases be explained? The last commit is from end of July while the `1.0.18-4.3.1` was released a day ago. I am just trying to understand your release system and where I can find more information about them

**Comment by wing328** [comment]
Unfortunately we don't have a release note or changelog for this particular repo. The best is to go through the commit logs as I remember we only fixed 2 or 3 issues due to external changes beyond our control. Have a nice weekend.
