### ISSUE TITLE
C# Client Library when generated through openapi-generator-cli adds two authorization headers.

### ISSUE THREAD

**Issue by ng13548** [OpenAPITools/openapi-generator-cli#394]
We have created a microservice using nest js. we are using openapi-generator-cli to generate client sdks. We are using swagger to consume open api definition. We have configured  OAuth2 for 'Try it out' on Swagger UI to work with protected routes and also configured bearer Auth using documentbuilder.addOAuth2().addBearerAuth().
While generating client SDK  for angular apps, it works perfectly fine -
![image](https://user-images.githubusercontent.com/86665207/123801069-8851e900-d907-11eb-95df-5f110e44e626.png)

But while generating client SDK in C# dotnet core using "openapi-generator-cli generate -g csharp-netcore -o XYZ/ -i openApi.json --additional-properties packageName=XYZ", we are unable to use it since two authorization headers were added in the generated code. It returns 401 on every API call through client SDK.
![image](https://user-images.githubusercontent.com/86665207/123800367-da463f00-d906-11eb-9902-fabce779eee7.png)

**Comment by ng13548** [comment]
why is this issue closed? Can you explain?

**Comment by kay-schecker** [comment]
Because of:

![image](https://user-images.githubusercontent.com/30752021/124021517-ec4ddd80-d9eb-11eb-9d4d-d69775105202.png)

and:

![image](https://user-images.githubusercontent.com/30752021/124021558-f8399f80-d9eb-11eb-9123-0ee7e72c9b22.png)

**Comment by ng13548** [comment]
aaah ! got it thanks!
