### ISSUE TITLE
[BUG] Broken dependencies in 2.3.6: Nestjs 7.6.x is not compatible with rxjs 7.x.x

### ISSUE THREAD

**Issue by LaurensUP** [OpenAPITools/openapi-generator-cli#416]
# 🐛 Bug Report:

### Describe the bug
Nestjs 7.6.x is not compatible with rxjs 7.x.x
We encountered this issue when upgrading to yarn 2.
``` bash
➤ YN0060: │ @openapitools/openapi-generator-cli@npm:2.3.6 provides rxjs (p54f62) with version 7.2.0, which doesn't satisfy what @nestjs/common requests
➤ YN0060: │ @openapitools/openapi-generator-cli@npm:2.3.6 provides rxjs (pfb08d) with version 7.2.0, which doesn't satisfy what @nestjs/core requests
```

### Steps to Reproduce
1. Create a new project using yarn 2
2. Add dependency on "@openapitools/openapi-generator-cli": "^2.3.6"
3. Run `yarn`

### Expected behavior
"@openapitools/openapi-generator-cli": "^2.3.6" uses nestjs version 8.x.x or rxjs v 6.x.x

### Operation System (please complete the following information):
 - OS: all

### Package System (please complete the following information):
 - Version yarn 2.4.2

**Comment by alex-marczinek** [comment]
@kay-schecker Are there any plans to upgrade to nest v8 in the near future?

**Comment by kay-schecker** [comment]
done in v 2.4.3
