### ISSUE TITLE
NPM package with jar already embedded

### ISSUE THREAD

**Issue by tobley** [OpenAPITools/openapi-generator-cli#42]
The version manager and ability to select which version of the openapi-generator jar to use is nice. However, it presumes every development environment has unfettered internet access that allows openapi-generator-cli to access the hardcoded URLs for search and download. This isn't always the case.

It would be convenient for the internet impaired to have a released NPM package that bundles the latest stable jar so the cli can just run out of the box without additional download.

I'm sure the jar can be downloaded separately and dropped into a directory to prevent the download. This means I have to manually manage the dependencies of my NPM dependencies which doesn't seem ideal.

**Comment by kay-schecker** [comment]
Unfortunately this is technically not possible under consideration of SemVer, because an existing version cannot be overwritten at NPM.

**Comment by gunta** [comment]
There are multiple cases where this makes sense.
What about publishing a separate package for it?
