### ISSUE TITLE
[BUG]   In generated project, in package.json, we have "version": "1.0" instead of "version": "1.0.0"

### ISSUE THREAD

**Issue by yidongw** [OpenAPITools/openapi-generator-cli#426]
# ⚠️ Important Notice

### Please differentiate the bug

This repository is not responsible for the actual code generation. If you have problems with the code generation, please open the bug at [OpenAPITools/openapi-generator](https://github.com/OpenAPITools/openapi-generator). 

Please also check if the bug is already known before you open a new bug.

----------------------------------------------------------------------------

# 🐛 Bug Report:

### Describe the bug
complaining the version when I trying to run the project

### Steps to Reproduce
1. run `npx openapi-generator-cli generate -i tacen-compliance-api.v1.yaml -g nodejs-express-server -o ./dist/server/`
2. go to the folder and run `npm start`

### Expected behavior
it should run

### Operation System (please complete the following information):
 - OS: Mac
 - Version 10.13.6

### Package System (please complete the following information):
- node: v12.18.4
- npm: 6.14.6
- @openapitools/openapi-generator-cli: "^2.3.8"

**Comment by kay-schecker** [comment]
⚠️ Important Notice
Please differentiate the bug
This repository is not responsible for the actual code generation. If you have problems with the code generation, please open the bug at OpenAPITools/openapi-generator.

Please also check if the bug is already known before you open a new bug.
