### ISSUE TITLE
[BUG] Passing additional parameters white spaces fails

### ISSUE THREAD

**Issue by osimosu** [OpenAPITools/openapi-generator-cli#447]
I'm unable to pass additional parameters with space to the CLI.

CLI Version
`@openapitools/openapi-generator-cli@2.3.10
`
I installed the CLI with:
`npm install @openapitools/openapi-generator-cli -g`

This works:
`openapi-generator-cli generate -g java -o ava-server-sdk -i https://test.com/v1.yaml --additional properties=artifactDescription=My`

This doesn't
`openapi-generator-cli generate -g java -o java-server-sdk -i https://test.com/v1.yaml --additional properties=artifactDescription=My SDK`

`openapi-generator-cli generate -g java -o java-server-sdk -i https://test.com/v1.yaml --additional-properties=artifactDescription='My SDK'`

`openapi-generator-cli generate -g java -o ava-server-sdk -i https://test.com/v1.yaml --additional-properties=artifactDescription="My SDK"`

The error:
`[error] Found unexpected parameters: [SDK]`

### Operation System (please complete the following information):
 - OS: Windows
 - Version 10

### Package System (please complete the following information):
 - Npm 7.6.0

**Comment by kevineaton603** [comment]
The value for `additional-properties` looks like it needs to be wrapped in quotes. Have you tried? 

`openapi-generator-cli generate -g java -o ava-server-sdk -i https://test.com/v1.yaml --additional-properties="artifactDescription=\"My SDK\""`

**Comment by osimosu** [comment]
@kevineaton603 That worked!! thanks
