### ISSUE TITLE
Overriding templates

### ISSUE THREAD

**Issue by metalcamp** [OpenAPITools/openapi-generator-cli#456]
Hello, thank you for this awesome package! 

I was looking through docs and couldn't find a way to override templates (for example for tsconfig.json or package.json). I've seen that the original package that takes care of code generation already enables that. Does this wrapper pass parameters directly to the original package or it has to be implemented first?

Thank you.

**Comment by kay-schecker** [comment]
Hey thanks :) This wrapper will forward all arguments to the original package.

**Comment by metalcamp** [comment]
Just found out I could use templateDir parameter in config and I can override all the templates in there. Templates can be found [here](https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/). 

`{
  "$schema": "node_modules/@openapitools/openapi-generator-cli/config.schema.json",
  "spaces": 2,
  "generator-cli": {
    "version": "5.2.1",
    "generators": {
      "ts-fetch": {
        "generatorName": "typescript-fetch",
        "templateDir": "#{cwd}/templates/typescript-fetch/",
        "output": "#{cwd/packates/fetch-client/",
        "glob": "swagger.resolved.{json,yaml}",
        "additionalProperties": {
          "npmName": "fetch-client",
          "supportsES6": "true",
          "typescriptThreePlus": true,
          "noRuntimeChecks": true
        }
      },
      "ts-node": {
        "generatorName": "typescript-node",
        "templateDir": "#{cwd}/templates/typescript-node/",
        "output": "#{cwd}/packages/node-client/",
        "glob": "swagger.resolved.{json,yaml}",
        "additionalProperties": {
          "npmName": "node-client",
          "supportsES6": "true",
          "typescriptThreePlus": true,
          "noRuntimeChecks": true
        }
      }
    }
  }
}
`
