### ISSUE TITLE
What is the glob property?

### ISSUE THREAD

**Issue by kevineaton603** [OpenAPITools/openapi-generator-cli#457]
Somewhat new to this package so I wondering what is the `glob` property? I am assuming that it is swagger doc that I want to generate from but then what is the difference between `glob` and `input-spec`? Also why can't `glob` be a url?

**Comment by kay-schecker** [comment]
By using a glob u can use the same generator config for multiple files. For each file matching the glob the configuration is applied. Within the configuration itself placeholders are available: https://github.com/OpenAPITools/openapi-generator-cli/blob/master/apps/generator-cli/src/README.md#available-placeholders

**Comment by omeralper** [comment]
why can't it be url?
