### ISSUE TITLE
Error  UnhandledPromiseRejectionWarning: ... "java" not found

### ISSUE THREAD

**Issue by squadwuschel** [OpenAPITools/openapi-generator-cli#520]
# 🐛 Bug Report:

### Describe the bug

I am trying to generate the service with yaml from the petstore for typescript-fetch with the following npm command, but Its not generating any code and I am getting a error sorry just in german I've tried to translate it

  
       (node:23588) UnhandledPromiseRejectionWarning: Error: The command "java" is either misspelled or
        could not be found.

### Steps to Reproduce
I've just installed the open-api generator like descriped into my project and also globaly with the current version: 2.4.12

      openapi-generator-cli generate -i https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml --generator-name typescript-fetch -o /httpServices

### Expected behavior
the client is created

### Screenshots
![grafik](https://user-images.githubusercontent.com/1572878/137642747-b34a033a-fe96-43eb-ba95-30f50edeaef7.png)

### Operation System (please complete the following information):
 - OS: Windows 10

**Comment by ardc-shorn** [comment]
https://github.com/OpenAPITools/openapi-generator-cli/pull/662
