### ISSUE TITLE
[Feature request, Angular / Typescript] Type instead of multiple properties for QueryParams

### ISSUE THREAD

**Issue by angelaki** [OpenAPITools/openapi-generator-cli#613]
In my opinion it would be nice the pass an object instread of multiple values to the generated api service. If the arguments' orders change this can simply cause problems without noticing it.

E.g. instead of 

`public GetValues(a?: string, b?: string, c?: string, d?: string, e?: string, f?: boolean, g?: boolean, h?: boolean, i?: number, j?: number, k?: number, l?: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext})` 

I'd rather use 

`public GetValues(query: { a?: string, b?: string, c?: string, d?: string, e?: string, f?: boolean, g?: boolean, h?: boolean, i?: number, j?: number, k?: number, l?: number }, observe: any = 'body', reportProgress: boolean = false, options?: { httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext})`

**Comment by dbrils** [comment]
Check out the `useSingleRequestParameter` config option: https://openapi-generator.tech/docs/generators/typescript-angular/

**Comment by angelaki** [comment]
Thank you so much! Exactly what I was looking for!

**Comment by angelaki** [comment]
Almost exactly what I was looking for ;) Would be nice if:

- Single parameters wouldn't be wrapped in RequestParams
- If all properties are optional, the RequestParams would be optional, too

Where to spread these ideas? ;)

**Comment by angelaki** [comment]
Do you want me to open a new issue for this idea?

`Single parameters wouldn't be wrapped in RequestParams` is a bit confusing, guess it's discussable / unneccessary. But I think `If all properties are optional, the RequestParams would be optional, too` is quite handy!

**Comment by kay-schecker** [comment]
No, please see https://github.com/OpenAPITools/openapi-generator-cli/issues/31

**Comment by angelaki** [comment]
Oh, ok! Ty so much!
