### ISSUE TITLE
[question]  Hello. Is it possible to disable the unloading of the jar file from the repository during the build?

### ISSUE THREAD

**Issue by ZaharovDm** [OpenAPITools/openapi-generator-cli#616]
Hello. Is it possible to disable the unloading of the jar file from the repository during the build? 
The fact is that we are using a closed nexus and an error occurs when trying to upload a jar file

**Comment by kay-schecker** [comment]
This package does not upload anything. It downloads the jar from a maven registry. It's possible to configure the download for a private registry. Please see https://github.com/OpenAPITools/openapi-generator-cli#using-custom--private-maven-registry
