### ISSUE TITLE
Cannot download openapi-generator when using Yarn2 PnP

### ISSUE THREAD

**Issue by chriswoodle** [OpenAPITools/openapi-generator-cli#67]
Hello, 

I seem to have an issue getting openapi-generator-cli to download openapi-generator when using [Yarn PnP](https://yarnpkg.com/features/pnp) locally.

openapi-generator-cli fails to download openapi-generator because the directory it tries to write to is virtual. Yarn PnP unpacks zipped dependencies at runtime and therefore openapi-generator-cli cannot write to node_modules.

![image](https://user-images.githubusercontent.com/11614325/95671347-e49b8f80-0b63-11eb-836a-ed8c377187c4.png)

Maybe a way to set the download directory in some config could get around the issue? For now I have to use openapi-generator-cli from a global install.

Thanks

**Comment by kay-schecker** [comment]
Thanks for the hint. I already had the configuration value for the location in mind :) I will add it in the next days. ✌️

**Comment by kay-schecker** [comment]
The new storage option is available now. (v2.1.3)
