### ISSUE TITLE
[BUG] outdated dependencies, specifically @nestjs/core

### ISSUE THREAD

**Issue by seanmc86** [OpenAPITools/openapi-generator-cli#692]
# 🐛 Bug Report:

It appears that many dependencies used have fixed version numbers in package.json and have not been updated in some time.

### Describe the bug

@nestjs/core has a vulnerability raised by dependabot: "@nestjs/core vulnerable to Information Exposure via StreamableFile pipe"
The @nestjs/core version 8.4.4 was released nearly a year ago: https://github.com/nestjs/nest/releases/tag/v8.4.4

I'd recommend updating this dependency as soon as possible, and investigating others that may also be outdated.

**Comment by OptoCloud** [comment]
This should be getting fixed in this PR #693

**Comment by kradical** [comment]
It would be nice to upgrade to `9.0.5` or greater to avoid the security vulnerability. Or you could unpin the dependency doing something like "^9.0.5" to allow consumers to sidestep future vulnerabilities without a change to this library.

**Comment by TheOlinone** [comment]
> This should be getting fixed in this PR #693

It appears that said PR was merged but no new release was made?
Any chance this will be released soon?

**Comment by ribeaud** [comment]
I think we are all waiting... It is annoying to get **2 moderate severity vulnerabilities** on each `npm i` run. Anyone available here?

**Comment by wiesnery** [comment]
Hi there,
Could we do a bigger version update of all outdated dependencies?
I could assist and create the PR, but only if I see any movement from the moderators e.g. @wing328

**Comment by wing328** [comment]
@wiesnery yes please file a PR and we will definitely work with you and the community to try to get it merged

**Comment by wing328** [comment]
thanks @erehulka for filing https://github.com/OpenAPITools/openapi-generator-cli/pull/837 to update nest js dependencies.

if no further question, i'll merge it later this week

According to @erehulka

> There are still however several outdated nx packages, I would need some help with that.

If anyone would like help with that, please file a PR when you've time.

**Comment by erehulka** [comment]
@wing328 I have updated the `@nx` packages to the latest versions, using their update script: https://nx.dev/features/automate-updating-dependencies#step-4-update-community-plugins-optional.

So far after my testing everything works correctly. However if some error arises, it is only in the last commit and can easily be reverted (it is in the mentioned PR)

**Comment by wing328** [comment]
update: merged and included in the latest release: https://github.com/OpenAPITools/openapi-generator-cli/releases/tag/v2.15.0

did a test and everything works fine for me so far.

thanks again for the PRs
