### ISSUE TITLE
 Failed to run the command for setting the version `openapi-generator-cli version-manager set 5.3.0`

### ISSUE THREAD

**Issue by huhouhua** [OpenAPITools/openapi-generator-cli#713]
# 🐛 Bug Report:

### Describe the bug
 Description Failed to run the command for setting the version `openapi-generator-cli version-manager set 5.3.0`

### Describe the bug
1. execute `openapi-generator-cli version-manager set 5.3.0`
![image](https://github.com/OpenAPITools/openapi-generator-cli/assets/40319281/8940b8b0-f94a-4cff-a5eb-a0b73771bd66)

**Comment by wing328** [comment]
you will need JDK 11 or newer versions
