### ISSUE TITLE
[UPDATE] Release 7.1.0

### ISSUE THREAD

**Issue by jakubno** [OpenAPITools/openapi-generator-cli#720]
Can you please release version 7.1.0?

**Comment by jakubno** [comment]
I see 7.1.0 as released https://github.com/OpenAPITools/openapi-generator/releases/tag/v7.1.0, but I don't see it in CLI. Am I doing something wrong? 

I am using latest version of CLI and in `version-manager` I don't see `7.1.0`. When I try to set it explicitly by `version-manager set 7.1.0`. I am receiving: `Unable to find version matching criteria "7.1.0"`

**Comment by wing328** [comment]
looks like search.maven.org hasn't picked up the latest release v7.1.0 yet: https://search.maven.org/solrsearch/select?q=g:org.openapitools+AND+a:openapi-generator-cli&core=gav&start=0&rows=200

please use the CLI JAR directly for the time being

**Comment by jakubno** [comment]
Thanks!
