### ISSUE TITLE
[BUG] cant run docker-entrypoint.sh anymore | bash missing :(

### ISSUE THREAD

**Issue by Gerrri** [OpenAPITools/openapi-generator-cli#721]
# 🐛 Bug Report:

### Describe the bug
bash is not in the base image (of openapi-generator) anymore, thats why docker-entrypoint.sh cant be run anymore

### Steps to Reproduce
run docker-entrypoint.sh

### Expected behavior
you can run docker-entrypoint.sh

### Additional
using Version 7.10 works

**Comment by wing328** [comment]
Please use v7.1.0 for time being

I will try to fix it shortly

**Comment by wing328** [comment]
i think this has been resolved. let me know if that's not the case
