### ISSUE TITLE
openapi-generator-cli couldn't list installed versions

### ISSUE THREAD

**Issue by nprajesh** [OpenAPITools/openapi-generator-cli#753]
I tried to install `openapi-generator-cli` using following command. `npm install @openapitools/openapi-generator-cli -g` and tried to list installed versions with `openapi-generator-cli version-manager list`. 

It throws an error as:
```
Error
    at C:\Users\rk\AppData\Roaming\npm\node_modules\@openapitools\openapi-generator-cli\main.js:2:27016
    at ChildProcess.exithandler (node:child_process:430:5)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:517:28)
    at Pipe.<anonymous> (node:net:350:12)
```

Node version: v18.19.0, openapi-generator-cli: 7.2.0, Windows

It was working fine on version 6.4.0, all of a sudden it stopped working. Then I had tried installing different version of `openapi-generator-cli` but it didn't work.

**Comment by wing328** [comment]
can you try uninstall and install it again?

please also use DOS prompt.

**Comment by nprajesh** [comment]
@wing328 I tried uninstalling and installing again with DOS prompt. It's the same.

**Comment by wing328** [comment]
is your machine behind a proxy or firewall?

**Comment by nprajesh** [comment]
I am using VPN, there must be a firewall.

**Comment by wing328** [comment]
Sorry no idea. As a workaround you may want to download the CLI JAR and use it directly, or use the Docker image instead: https://hub.docker.com/r/openapitools/openapi-generator-cli

**Comment by nprajesh** [comment]
Installing Java again solved the problem.

**OS**
Windows: Windows 10 Enterprise
Version: 10.0.19045 Build 19045

**Java**
java version "1.8.0_401"

**Node**
v18.19.0
