### ISSUE TITLE
NPM @openapitools/openapi-generator-cli package is not the latest

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenAPITools/openapi-generator-cli#783]
I tried the latest version [1.0.18-4.3.1](https://www.npmjs.com/package/@openapitools/openapi-generator-cli/v/1.0.18-4.3.1) and got the openapi-generator.jar for `5.0.0-beta2`. The [2.13.4](https://www.npmjs.com/package/@openapitools/openapi-generator-cli/v/2.13.4) does not embed the jar.

Can provide a new version for latest openapi-generator [7.5.0](https://github.com/OpenAPITools/openapi-generator/releases/tag/v7.5.0)?

**Comment by wing328** [comment]
we no longer maintain the 1.x version of openapi-generator-cli.

please upgrade to the latest 2.x version, which can set to download the latest openapi-generator-cli JAR (7.5.0)
