### ISSUE TITLE
404 config.schema.json

### ISSUE THREAD

**Issue by FDiskas** [OpenAPITools/openapi-generator-cli#786]
The path to the schema `https://openapitools.org/openapi-generator-cli/config.schema.json` leads to 404
https://github.com/OpenAPITools/openapi-generator-cli/blob/6b76bbbbc10630190289a32b7ecafce61cd3ab12/apps/generator-cli/src/config.schema.json#L2C11-L2C76

**Comment by kemotx90** [comment]
in your openapitools.json use

```typescript
{
  "$schema": "node_modules/@openapitools/openapi-generator-cli/config.schema.json",
  ...
}
```
