### ISSUE TITLE
[Dependency update] - Vulnerable axios dependency

### ISSUE THREAD

**Issue by kemotx90** [OpenAPITools/openapi-generator-cli#792]
# 🐛 Report:

### Describe the bug
Current version use vulnerable axios dependency

- [ ] [Server-Side Request Forgery in axios](https://github.com/advisories/GHSA-8hc4-vh64-cxmj)

### Expected behavior
Axios >1.7.3

### Screenshots
![immagine](https://github.com/user-attachments/assets/fe9dcf82-8e68-4231-a16b-b8f23d189294)

### Operation System (please complete the following information):
 - OS: Windows
 - Version 10

### Package System (please complete the following information):
 - Version 2.13.4

**Comment by markus-ebner** [comment]
Should be resolved in https://github.com/OpenAPITools/openapi-generator-cli/pull/789#pullrequestreview-2245402855 but it still needs approval from a contributor :)

**Comment by TimoReckling** [comment]
> Should be resolved in [#789 (review)](https://github.com/OpenAPITools/openapi-generator-cli/pull/789#pullrequestreview-2245402855) but it still needs approval from a contributor :)

But don't we also need an update of @nestjs/axios to its newest version such that that also uses axios 1.7.4 https://github.com/nestjs/axios/releases/tag/3.0.3

**Comment by TimoReckling** [comment]
@kay-schecker  I don't know if you got assigned or assigned yourself, but can you have a look at this security update?

**Comment by wing328** [comment]
i just merged #789 

please give it a try with the latest release. thanks
