### ISSUE TITLE
[BUG] Security issue: path-to-regexp outputs backtracking regular expressions please update nestjs/core

### ISSUE THREAD

**Issue by dvag-oezkan-yalcinkaya** [OpenAPITools/openapi-generator-cli#804]
See this: https://github.com/nestjs/nest/issues/13955

please update nestjs/core to version 10.4.3

**Comment by wing328** [comment]
can you please file a PR with the update?

**Comment by wing328** [comment]
https://github.com/OpenAPITools/openapi-generator-cli/pull/801

will ask the author to update his PR accordingly

thanks for informing us
