### ISSUE TITLE
[BUG] Unable to query repository, because of: "Request failed with status code 504"

### ISSUE THREAD

**Issue by ricofairsailcom** [OpenAPITools/openapi-generator-cli#806]
# 🐛 Bug Report:

### Describe the bug
There is an error when validating the documentation

when running locally we can see the error
```
$ openapi-generator-cli validate -i openapi.yaml
Unable to query repository, because of: "Request failed with status code 504"

Response:
content-type text/html
content-length 1033
connection close
server CloudFront
date Thu, 19 Sep 2024 10:40:58 GMT
x-cache Error from cloudfront
via 1.1 63da3f90bf5fee6becace4e37df3b244.cloudfront.net (CloudFront)
x-amz-cf-pop LHR61-P7
x-amz-cf-id Nyg4B57GMKNqQEf1G-nXlI-27ZOY_IWWCXa6J8b3BFCKx8S5ZeemIw==
x-xss-protection 1; mode=block
x-frame-options SAMEORIGIN
referrer-policy strict-origin-when-cross-origin
x-content-type-options nosniff
strict-transport-security max-age=31536000          
```
### Package System (please complete the following information):
 - Version 2.13.7

**Comment by Shuyinsama** [comment]
Same issue here. Trying if downgrading the package works

**Comment by jupie** [comment]
Same with 2.13.5

**Comment by sharonamr** [comment]
This seems to be flaky. It actually worked with `2.13.5` but also worked with `2.13.7` in 1 out of 5 tries 😵‍💫

**Comment by MatthewMazaika** [comment]
this looks like one of the behaviors seen in #802 when search.maven.org was having an outage

**Comment by wing328** [comment]
please give it a try with the latest stable version 2.13.9

to completely bypass making a request to https://search.maven.org/, simply set the environment variable OPENAPI_GENERATOR_CLI_SEARCH_URL to DEFAULT, e.g. https://github.com/OpenAPITools/openapi-generator-cli/blob/master/.github/workflows/build.yml#L87
