### ISSUE TITLE
[BUG] Openapi normalizer argument not passed to the generator

### ISSUE THREAD

**Issue by ChamNouki** [OpenAPITools/openapi-generator-cli#824]
# 🐛 Bug Report:

### Describe the bug
generator arguments [--openapi-normalizer](https://openapi-generator.tech/docs/customization/#openapi-normalizer) seems not possible to be passed through the node CLI wrapper.

### Steps to Reproduce
I've tryed to find this option in openapitools.json schema or passing it directly in the npm script `openapi-generator-cli generate --openapi-normalizer KEEP_ONLY_FIRST_TAG_IN_OPERATION=true` but that not seems to be passed to the generator seems generated sources for my endpoint are generated for both tags placed on in my openapi contract.

concerned extract of my openapicontract :
```yml
  /products/{gtin13}:
    description: 
    get:
      operationId: getProduct
      summary: 
      tags:
        - products
        - supplier
      parameters:
        - name: gtin13
          in: path
          schema:
            type: string
          required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: The related Product
```

### Expected behavior
Could it be possible to specify openapi normalizer variable in generators specification in the openapitools.json or directly by the CLI ?

### Operation System (please complete the following information):
 - OS: Mac OS
 - Version 15.0 

### Package System (please complete the following information):
 - Version 2.13.12

**Comment by ChamNouki** [comment]
It seems to be possible to pass it to the generator command by specifying it in openapitools.json despite the json schema. So I open a PR to suggest a schema update : #830

**Comment by wing328** [comment]
i tested with the following and it works without issue:
```
openapi-generator-cli generate -g ruby -i https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml -o C:\temp\ruby-client --openapi-normalizer SET_TAGS_TO_OPERATIONID=true
```

what errors did you get when using openapi normalizer with the CLI wrapper?

**Comment by ChamNouki** [comment]
I didn't get any error, but the `--openapi-normalizer` cli arguments seems to be taken into account.

After investigating further more the `--openapi-normalizer` cli arguments seems to be ignored or override when using `--generator-key` even when used generator does not define `openapi-normalizer` property in json config.

So the conclusion is 
1. use `--openapi-normalizer` cli arguments but not `--generator-key`
2. use `openapi-normalizer` property in generator json config when using `--generator-key` cli argument
